#!/usr/bin/env python3
"""
This module provides a coroutine that uses an async comprehension
to collect 10 random float numbers generated by async_generator.
"""
from typing import List

async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    Collects 10 random numbers using an async comprehension over
    async_generator and returns the collected list of floats.
    """
    return [i async for i in async_generator()]
